// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnInfo describes a connection with its current field values.
 */
export class ConnInfo {
    /**
     * Creates a new ConnInfo instance.
     * @param {Partial<ConnInfo>} [$$source = {}] - The source object to create the ConnInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("typeLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["typeLabel"] = "";
        }
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("tunnel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("isProxy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isProxy"] = false;
        }
        if (!("isOAuth" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isOAuth"] = false;
        }
        if (!("oauthOK" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["oauthOK"] = false;
        }
        if (!("isERP" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isERP"] = false;
        }
        if (!("isDeviceAuth" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDeviceAuth"] = false;
        }
        if (!("deviceAuthOK" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["deviceAuthOK"] = false;
        }
        if (!("readOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["readOnly"] = false;
        }
        if (!("instructions" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instructions"] = "";
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {FieldInfo[]}
             */
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnInfo}
     */
    static createFrom($$source = {}) {
        const $$createField15_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField15_0($$parsedSource["fields"]);
        }
        return new ConnInfo(/** @type {Partial<ConnInfo>} */($$parsedSource));
    }
}

/**
 * DeviceAuthStart is returned by StartDeviceAuth().
 */
export class DeviceAuthStart {
    /**
     * Creates a new DeviceAuthStart instance.
     * @param {Partial<DeviceAuthStart>} [$$source = {}] - The source object to create the DeviceAuthStart.
     */
    constructor($$source = {}) {
        if (!("userCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userCode"] = "";
        }
        if (!("verificationURI" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["verificationURI"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceAuthStart instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceAuthStart}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceAuthStart(/** @type {Partial<DeviceAuthStart>} */($$parsedSource));
    }
}

/**
 * DeviceAuthStatus is returned by GetDeviceAuthStatus().
 */
export class DeviceAuthStatus {
    /**
     * Creates a new DeviceAuthStatus instance.
     * @param {Partial<DeviceAuthStatus>} [$$source = {}] - The source object to create the DeviceAuthStatus.
     */
    constructor($$source = {}) {
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceAuthStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceAuthStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceAuthStatus(/** @type {Partial<DeviceAuthStatus>} */($$parsedSource));
    }
}

/**
 * ERPInfo describes ERP provisioning status.
 */
export class ERPInfo {
    /**
     * Creates a new ERPInfo instance.
     * @param {Partial<ERPInfo>} [$$source = {}] - The source object to create the ERPInfo.
     */
    constructor($$source = {}) {
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (!("tokenSet" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tokenSet"] = false;
        }
        if (!("tunnels" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tunnels"] = 0;
        }
        if (!("connections" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connections"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["resultMessage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["resultSuccess"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ERPInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ERPInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ERPInfo(/** @type {Partial<ERPInfo>} */($$parsedSource));
    }
}

/**
 * FieldInfo describes a single form field for a connection.
 */
export class FieldInfo {
    /**
     * Creates a new FieldInfo instance.
     * @param {Partial<FieldInfo>} [$$source = {}] - The source object to create the FieldInfo.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("placeholder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["placeholder"] = "";
        }
        if (!("secret" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["secret"] = false;
        }
        if (!("small" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["small"] = false;
        }
        if (!("secretStored" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["secretStored"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FieldInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FieldInfo(/** @type {Partial<FieldInfo>} */($$parsedSource));
    }
}

/**
 * OAuthStartResult is returned by StartOAuth().
 */
export class OAuthStartResult {
    /**
     * Creates a new OAuthStartResult instance.
     * @param {Partial<OAuthStartResult>} [$$source = {}] - The source object to create the OAuthStartResult.
     */
    constructor($$source = {}) {
        if (!("authURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OAuthStartResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OAuthStartResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OAuthStartResult(/** @type {Partial<OAuthStartResult>} */($$parsedSource));
    }
}

/**
 * OAuthStatus is returned by GetOAuthStatus().
 */
export class OAuthStatus {
    /**
     * Creates a new OAuthStatus instance.
     * @param {Partial<OAuthStatus>} [$$source = {}] - The source object to create the OAuthStatus.
     */
    constructor($$source = {}) {
        if (!("authorized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["authorized"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OAuthStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OAuthStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OAuthStatus(/** @type {Partial<OAuthStatus>} */($$parsedSource));
    }
}

/**
 * PageData is the top-level structure returned by GetPageData().
 */
export class PageData {
    /**
     * Creates a new PageData instance.
     * @param {Partial<PageData>} [$$source = {}] - The source object to create the PageData.
     */
    constructor($$source = {}) {
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {ServerInfo}
             */
            this["server"] = (new ServerInfo());
        }
        if (!("erp" in $$source)) {
            /**
             * @member
             * @type {ERPInfo}
             */
            this["erp"] = (new ERPInfo());
        }
        if (!("tunnels" in $$source)) {
            /**
             * @member
             * @type {TunnelInfo[]}
             */
            this["tunnels"] = [];
        }
        if (!("connections" in $$source)) {
            /**
             * @member
             * @type {ConnInfo[]}
             */
            this["connections"] = [];
        }
        if (!("types" in $$source)) {
            /**
             * @member
             * @type {TypeListEntry[]}
             */
            this["types"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PageData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PageData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("server" in $$parsedSource) {
            $$parsedSource["server"] = $$createField0_0($$parsedSource["server"]);
        }
        if ("erp" in $$parsedSource) {
            $$parsedSource["erp"] = $$createField1_0($$parsedSource["erp"]);
        }
        if ("tunnels" in $$parsedSource) {
            $$parsedSource["tunnels"] = $$createField2_0($$parsedSource["tunnels"]);
        }
        if ("connections" in $$parsedSource) {
            $$parsedSource["connections"] = $$createField3_0($$parsedSource["connections"]);
        }
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField4_0($$parsedSource["types"]);
        }
        return new PageData(/** @type {Partial<PageData>} */($$parsedSource));
    }
}

/**
 * SaveConnectionRequest contains the fields to save for a connection.
 */
export class SaveConnectionRequest {
    /**
     * Creates a new SaveConnectionRequest instance.
     * @param {Partial<SaveConnectionRequest>} [$$source = {}] - The source object to create the SaveConnectionRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["host"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["user"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["database"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["token"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["scopes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tunnel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["instructions"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveConnectionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveConnectionRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveConnectionRequest(/** @type {Partial<SaveConnectionRequest>} */($$parsedSource));
    }
}

/**
 * SaveTunnelRequest contains the fields to save for a tunnel.
 */
export class SaveTunnelRequest {
    /**
     * Creates a new SaveTunnelRequest instance.
     * @param {Partial<SaveTunnelRequest>} [$$source = {}] - The source object to create the SaveTunnelRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["peerPublicKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["peerEndpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["allowedIPs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tunnelAddress"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mtu"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["keepAlive"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["privateKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["presharedKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["host"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["user"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["keyFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["insecureHostKey"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveTunnelRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveTunnelRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveTunnelRequest(/** @type {Partial<SaveTunnelRequest>} */($$parsedSource));
    }
}

/**
 * ServerInfo contains version/uptime metadata shown in the header.
 */
export class ServerInfo {
    /**
     * Creates a new ServerInfo instance.
     * @param {Partial<ServerInfo>} [$$source = {}] - The source object to create the ServerInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("uptime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uptime"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("buildTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerInfo(/** @type {Partial<ServerInfo>} */($$parsedSource));
    }
}

/**
 * TestResult is returned by TestConnection().
 */
export class TestResult {
    /**
     * Creates a new TestResult instance.
     * @param {Partial<TestResult>} [$$source = {}] - The source object to create the TestResult.
     */
    constructor($$source = {}) {
        if (!("connection" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection"] = "";
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["latency"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult(/** @type {Partial<TestResult>} */($$parsedSource));
    }
}

/**
 * TunnelInfo describes a WireGuard or SSH tunnel.
 */
export class TunnelInfo {
    /**
     * Creates a new TunnelInfo instance.
     * @param {Partial<TunnelInfo>} [$$source = {}] - The source object to create the TunnelInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["peerEndpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tunnelAddress"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["peerPublicKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["allowedIPs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["mtu"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["keepAlive"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["host"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["user"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["keyFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["insecureHostKey"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("privateKeySet" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["privateKeySet"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["presharedKeySet"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelInfo(/** @type {Partial<TunnelInfo>} */($$parsedSource));
    }
}

/**
 * TypeListEntry is a single entry in the connection type picker.
 */
export class TypeListEntry {
    /**
     * Creates a new TypeListEntry instance.
     * @param {Partial<TypeListEntry>} [$$source = {}] - The source object to create the TypeListEntry.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TypeListEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TypeListEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TypeListEntry(/** @type {Partial<TypeListEntry>} */($$parsedSource));
    }
}

/**
 * UpdateResult is returned by SelfUpdate().
 */
export class UpdateResult {
    /**
     * Creates a new UpdateResult instance.
     * @param {Partial<UpdateResult>} [$$source = {}] - The source object to create the UpdateResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateResult(/** @type {Partial<UpdateResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = FieldInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ServerInfo.createFrom;
const $$createType3 = ERPInfo.createFrom;
const $$createType4 = TunnelInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ConnInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = TypeListEntry.createFrom;
const $$createType9 = $Create.Array($$createType8);
