// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails v3 service struct. All exported methods become frontend bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddConnection creates a new connection and returns its info.
 * @param {string} name
 * @param {string} typ
 * @returns {$CancellablePromise<$models.ConnInfo | null>}
 */
export function AddConnection(name, typ) {
    return $Call.ByID(2802565916, name, typ).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AddTunnel creates a new tunnel and returns its info.
 * @param {string} name
 * @param {string} typ
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function AddTunnel(name, typ) {
    return $Call.ByID(1252415046, name, typ).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DeleteConnection removes a local connection.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConnection(name) {
    return $Call.ByID(3428926502, name);
}

/**
 * DeleteTunnel removes a local tunnel.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTunnel(name) {
    return $Call.ByID(2127640780, name);
}

/**
 * GetConnection returns a single connection's info.
 * @param {string} name
 * @returns {$CancellablePromise<$models.ConnInfo | null>}
 */
export function GetConnection(name) {
    return $Call.ByID(1321857319, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetConnectionTypes returns available connection types for the add dialog.
 * @returns {$CancellablePromise<$models.TypeListEntry[]>}
 */
export function GetConnectionTypes() {
    return $Call.ByID(3128475076).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetDeviceAuthStatus checks if a device code auth flow has completed.
 * @param {string} name
 * @returns {$CancellablePromise<$models.DeviceAuthStatus | null>}
 */
export function GetDeviceAuthStatus(name) {
    return $Call.ByID(2894075289, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetOAuthStatus checks if an OAuth flow has completed.
 * @param {string} name
 * @returns {$CancellablePromise<$models.OAuthStatus | null>}
 */
export function GetOAuthStatus(name) {
    return $Call.ByID(2332662096, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetPageData returns the full page state (connections, tunnels, provisioning, server info).
 * @returns {$CancellablePromise<$models.PageData>}
 */
export function GetPageData() {
    return $Call.ByID(1840415772).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetServerInfo returns server metadata for the header.
 * @returns {$CancellablePromise<$models.ServerInfo>}
 */
export function GetServerInfo() {
    return $Call.ByID(3742070776).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * ReloadConnection re-registers MCP tools for a connection (implements tools.ToolReloader).
 * @param {config$0.Connection} conn
 * @returns {$CancellablePromise<void>}
 */
export function ReloadConnection(conn) {
    return $Call.ByID(2035036292, conn);
}

/**
 * SaveConnection saves connection fields and returns the updated info.
 * @param {string} name
 * @param {$models.SaveConnectionRequest} fields
 * @returns {$CancellablePromise<$models.ConnInfo | null>}
 */
export function SaveConnection(name, fields) {
    return $Call.ByID(865625064, name, fields).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SaveTunnel saves tunnel fields and returns the updated info.
 * @param {string} name
 * @param {$models.SaveTunnelRequest} fields
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function SaveTunnel(name, fields) {
    return $Call.ByID(814564682, name, fields).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SelfUpdate downloads the platform-specific binary and replaces the current one.
 * @returns {$CancellablePromise<$models.UpdateResult | null>}
 */
export function SelfUpdate() {
    return $Call.ByID(1021619070).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * SetupProvisioning saves provisioning endpoint and token.
 * @param {string} endpoint
 * @param {string} token
 * @returns {$CancellablePromise<$models.ProvisioningInfo | null>}
 */
export function SetupProvisioning(endpoint, token) {
    return $Call.ByID(2608126119, endpoint, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * StartDeviceAuth begins a device code auth flow (Microsoft Graph).
 * @param {string} name
 * @returns {$CancellablePromise<$models.DeviceAuthStart | null>}
 */
export function StartDeviceAuth(name) {
    return $Call.ByID(1416470487, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * StartOAuth begins an OAuth flow and returns the auth URL.
 * @param {string} name
 * @returns {$CancellablePromise<$models.OAuthStartResult | null>}
 */
export function StartOAuth(name) {
    return $Call.ByID(3241741926, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * SyncProvisioning fetches config from the provisioning server and returns updated page data.
 * @returns {$CancellablePromise<$models.PageData | null>}
 */
export function SyncProvisioning() {
    return $Call.ByID(1051342171).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * TestConnection tests a connection and returns the result.
 * @param {string} name
 * @returns {$CancellablePromise<$models.TestResult | null>}
 */
export function TestConnection(name) {
    return $Call.ByID(1257240193, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * TunnelLookup resolves a hostname through a WireGuard tunnel's DNS.
 * Only works for WireGuard tunnels (SSH tunnels do not provide DNS resolution).
 * @param {string} tunnelName
 * @param {string} hostname
 * @returns {$CancellablePromise<$models.TestResult | null>}
 */
export function TunnelLookup(tunnelName, hostname) {
    return $Call.ByID(2446815833, tunnelName, hostname).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * UnloadConnection removes MCP tools for a connection (implements tools.ToolReloader).
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function UnloadConnection(name) {
    return $Call.ByID(3348183438, name);
}

// Private type creation functions
const $$createType0 = $models.ConnInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.TunnelInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.TypeListEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.DeviceAuthStatus.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.OAuthStatus.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.PageData.createFrom;
const $$createType11 = $models.ServerInfo.createFrom;
const $$createType12 = $models.UpdateResult.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.ProvisioningInfo.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.DeviceAuthStart.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.OAuthStartResult.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $Create.Nullable($$createType10);
const $$createType21 = $models.TestResult.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
