// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Connection represents a database or proxy backend.
 */
export class Connection {
    /**
     * Creates a new Connection instance.
     * @param {Partial<Connection>} [$$source = {}] - The source object to create the Connection.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * see Type* constants in identifiers.go
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["host"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["user"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["database"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["readOnly"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["secure"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["token"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * proxy: use OAuth instead of bearer token
             * @member
             * @type {boolean | undefined}
             */
            this["oauth"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * OAuth client ID (microsoft-graph: Azure App Registration ID)
             * @member
             * @type {string | undefined}
             */
            this["clientId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["scopes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["instructions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * custom header name for token (default: "Authorization: Bearer {token}")
             * @member
             * @type {string | undefined}
             */
            this["tokenHeader"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * auth scheme: "" (bearer) or "basic"
             * @member
             * @type {string | undefined}
             */
            this["tokenScheme"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * non-secret constant placed after the token in Basic auth (token:suffix) when token_scheme=basic; a public constant, not a secret (e.g. Graylog "token", GitHub "x-oauth-basic")
             * @member
             * @type {string | undefined}
             */
            this["basicSuffix"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * name of a defined tunnel
             * @member
             * @type {string | undefined}
             */
            this["tunnel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * optional request limit per month
             * @member
             * @type {number | undefined}
             */
            this["monthlyLimit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * see Source* constants in identifiers.go
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Headers are extra HTTP headers sent with every request (http and proxy
             * types), e.g. API version headers like "Notion-Version: 2022-06-28". The
             * vault-managed token header always wins over an entry of the same name.
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["headers"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Connection}
     */
    static createFrom($$source = {}) {
        const $$createField21_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField21_0($$parsedSource["headers"]);
        }
        return new Connection(/** @type {Partial<Connection>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
